### ISSUE TITLE
怎么使用呢？

### ISSUE THREAD

**Issue by xsxsm** [Rikivt/postmarket_nubia_nx563j#2]
如题，我下载了release文件，解压后发现里面有boot 和 另一个文件。 我用twrp 刷入boot 和system  结果循环重启

**Comment by MarshJiang** [comment]
> 如题，我下载了release文件，解压后发现里面有boot 和 另一个文件。 我用twrp 刷入boot 和system  结果循环重启

使用fastboot刷入到userdata分区

**Comment by xsxsm** [comment]
> > 如题，我下载了release文件，解压后发现里面有boot 和 另一个文件。 我用twrp 刷入boot 和system  结果循环重启
> 
> 使用fastboot刷入到userdata分区
感谢，我用TWRP刷入boot.img后 ，然后我重启到bootloader模式，尝试使用fastboot flash userdata   nubia-nx563j.img 命令刷写 ，结果它卡住了Sending sparse 'userdata' 1/3 (494635 KB) ，这该咋办呢。 可以出一个刷入教程吗？  我刷了boot 后好像这个boot 不支持刷写，如果我要刷回原本boot 又该怎么做呢？

**Comment by MarshJiang** [comment]
> > > 如题，我下载了release文件，解压后发现里面有boot 和 另一个文件。 我用twrp 刷入boot 和system  结果循环重启
> 
> > 
> 
> > 使用fastboot刷入到userdata分区
> 
> 感谢，我用TWRP刷入boot.img后 ，然后我重启到bootloader模式，尝试使用fastboot flash userdata   nubia-nx563j.img 命令刷写 ，结果它卡住了Sending sparse 'userdata' 1/3 (494635 KB) ，这该咋办呢。 可以出一个刷入教程吗？  我刷了boot 后好像这个boot 不支持刷写，如果我要刷回原本boot 又该怎么做呢？

你bl锁解了吗？

**Comment by xsxsm** [comment]
> > > > 如题，我下载了release文件，解压后发现里面有boot 和 另一个文件。 我用twrp 刷入boot 和system  结果循环重启
> > 
> > 
> > > 
> > 
> > 
> > > 使用fastboot刷入到userdata分区
> > 
> > 
> > 感谢，我用TWRP刷入boot.img后 ，然后我重启到bootloader模式，尝试使用fastboot flash userdata   nubia-nx563j.img 命令刷写 ，结果它卡住了Sending sparse 'userdata' 1/3 (494635 KB) ，这该咋办呢。 可以出一个刷入教程吗？  我刷了boot 后好像这个boot 不支持刷写，如果我要刷回原本boot 又该怎么做呢？
> 
> 你bl锁解了吗？

我记得这个是可以直接刷来着， 我有执行过这个 fastboot oem nubia_unlock NUBIA_NX563J

**Comment by MarshJiang** [comment]
> > > > > 如题，我下载了release文件，解压后发现里面有boot 和 另一个文件。 我用twrp 刷入boot 和system  结果循环重启
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 使用fastboot刷入到userdata分区
> 
> > > 
> 
> > > 
> 
> > > 感谢，我用TWRP刷入boot.img后 ，然后我重启到bootloader模式，尝试使用fastboot flash userdata   nubia-nx563j.img 命令刷写 ，结果它卡住了Sending sparse 'userdata' 1/3 (494635 KB) ，这该咋办呢。 可以出一个刷入教程吗？  我刷了boot 后好像这个boot 不支持刷写，如果我要刷回原本boot 又该怎么做呢？
> 
> > 
> 
> > 你bl锁解了吗？
> 
> 
> 
> 我记得这个是可以直接刷来着， 我有执行过这个 fastboot oem nubia_unlock NUBIA_NX563J

那我就不知道你的设备咋回事了，只能是刷回安卓了

**Comment by xsxsm** [comment]
> 如题，我下载了release文件，解压后发现里面有boot 和 另一个文件。 我用twrp 刷入boot 和system 结果循环重启
这样算是刷完了吗，开机会无限重启，boot 是用twrp刷的哈。
fastboot flash userdata C:\Users\xx\Desktop\nubia-nx563j.img
Sending sparse 'userdata' 1/3 (494635 KB)          OKAY [ 16.531s]
Writing 'userdata'                                 OKAY [ 36.800s]
Sending sparse 'userdata' 2/3 (500188 KB)          OKAY [ 14.921s]
Writing 'userdata'                                 OKAY [  7.185s]
Sending sparse 'userdata' 3/3 (448023 KB)          OKAY [ 13.424s]
Writing 'userdata'                                 OKAY [ 29.061s]
Finished. Total time: 118.193s

**Comment by MarshJiang** [comment]
> > 如题，我下载了release文件，解压后发现里面有boot 和 另一个文件。 我用twrp 刷入boot 和system 结果循环重启
> 
> 这样算是刷完了吗，开机会无限重启，boot 是用twrp刷的哈。
> 
> fastboot flash userdata C:\Users\xx\Desktop\nubia-nx563j.img
> 
> Sending sparse 'userdata' 1/3 (494635 KB)          OKAY [ 16.531s]
> 
> Writing 'userdata'                                 OKAY [ 36.800s]
> 
> Sending sparse 'userdata' 2/3 (500188 KB)          OKAY [ 14.921s]
> 
> Writing 'userdata'                                 OKAY [  7.185s]
> 
> Sending sparse 'userdata' 3/3 (448023 KB)          OKAY [ 13.424s]
> 
> Writing 'userdata'                                 OKAY [ 29.061s]
> 
> Finished. Total time: 118.193s
> 
> 

我自己是都是用fastboot刷的，你试试看

**Comment by xsxsm** [comment]
> > > 如题，我下载了release文件，解压后发现里面有boot 和 另一个文件。 我用twrp 刷入boot 和system 结果循环重启
> > 
> > 
> > 这样算是刷完了吗，开机会无限重启，boot 是用twrp刷的哈。
> > fastboot flash userdata C:\Users\xx\Desktop\nubia-nx563j.img
> > Sending sparse 'userdata' 1/3 (494635 KB)          OKAY [ 16.531s]
> > Writing 'userdata'                                 OKAY [ 36.800s]
> > Sending sparse 'userdata' 2/3 (500188 KB)          OKAY [ 14.921s]
> > Writing 'userdata'                                 OKAY [  7.185s]
> > Sending sparse 'userdata' 3/3 (448023 KB)          OKAY [ 13.424s]
> > Writing 'userdata'                                 OKAY [ 29.061s]
> > Finished. Total time: 118.193s
> 
> 我自己是都是用fastboot刷的，你试试看

感谢，我重新下载了release解压 然后C:\Users\xx> fastboot flash boot C:\Users\xx\Desktop\nx563j-postmarketos\nx563j-postmarketos\boot.img
Warning: skip copying boot image avb footer (boot partition size: 0, boot image size: 7700480).
Sending 'boot' (7520 KB)                           OKAY [  0.191s]
Writing 'boot'                                     OKAY [  0.072s]
Finished. Total time: 0.271s

C:\Users\xx>fastboot flash userdata  C:\Users\xx\Desktop\nx563j-postmarketos\nx563j-postmarketos\nubia-nx563j.img
Sending sparse 'userdata' 1/3 (494635 KB)          OKAY [ 20.740s]
Writing 'userdata'                                 OKAY [ 36.643s]
Sending sparse 'userdata' 2/3 (500188 KB)          OKAY [ 21.686s]
Writing 'userdata'                                 OKAY [  7.162s]
Sending sparse 'userdata' 3/3 (448023 KB)          OKAY [ 19.304s]
Writing 'userdata'                                 OKAY [ 29.020s]
Finished. Total time: 134.670s

C:\Users\xx>fastboot reboot
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.001s
结果还是无限重启中

**Comment by MarshJiang** [comment]
> > > > 如题，我下载了release文件，解压后发现里面有boot 和 另一个文件。 我用twrp 刷入boot 和system 结果循环重启
> 
> > > 
> 
> > > 
> 
> > > 这样算是刷完了吗，开机会无限重启，boot 是用twrp刷的哈。
> 
> > > fastboot flash userdata C:\Users\xx\Desktop\nubia-nx563j.img
> 
> > > Sending sparse 'userdata' 1/3 (494635 KB)          OKAY [ 16.531s]
> 
> > > Writing 'userdata'                                 OKAY [ 36.800s]
> 
> > > Sending sparse 'userdata' 2/3 (500188 KB)          OKAY [ 14.921s]
> 
> > > Writing 'userdata'                                 OKAY [  7.185s]
> 
> > > Sending sparse 'userdata' 3/3 (448023 KB)          OKAY [ 13.424s]
> 
> > > Writing 'userdata'                                 OKAY [ 29.061s]
> 
> > > Finished. Total time: 118.193s
> 
> > 
> 
> > 我自己是都是用fastboot刷的，你试试看
> 
> 
> 
> 感谢，我重新下载了release解压 然后C:\Users\xx> fastboot flash boot C:\Users\xx\Desktop\nx563j-postmarketos\nx563j-postmarketos\boot.img
> 
> Warning: skip copying boot image avb footer (boot partition size: 0, boot image size: 7700480).
> 
> Sending 'boot' (7520 KB)                           OKAY [  0.191s]
> 
> Writing 'boot'                                     OKAY [  0.072s]
> 
> Finished. Total time: 0.271s
> 
> 
> 
> C:\Users\xx>fastboot flash userdata  C:\Users\xx\Desktop\nx563j-postmarketos\nx563j-postmarketos\nubia-nx563j.img
> 
> Sending sparse 'userdata' 1/3 (494635 KB)          OKAY [ 20.740s]
> 
> Writing 'userdata'                                 OKAY [ 36.643s]
> 
> Sending sparse 'userdata' 2/3 (500188 KB)          OKAY [ 21.686s]
> 
> Writing 'userdata'                                 OKAY [  7.162s]
> 
> Sending sparse 'userdata' 3/3 (448023 KB)          OKAY [ 19.304s]
> 
> Writing 'userdata'                                 OKAY [ 29.020s]
> 
> Finished. Total time: 134.670s
> 
> 
> 
> C:\Users\xx>fastboot reboot
> 
> Rebooting                                          OKAY [  0.000s]
> 
> Finished. Total time: 0.001s
> 
> 结果还是无限重启中

那就不知道咋回事了，不能启动的原因可能是boot校验，也可能是非原装机器，也可能你的机器跟我的硬件有区别

**Comment by xsxsm** [comment]
是不是这个问题呢，boot 没有刷成功skip  ？   Warning: skip copying boot image avb footer (boot partition size: 0, boot image size: 7700480).

**Comment by MarshJiang** [comment]
> 是不是这个问题呢，boot 没有刷成功skip  ？   Warning: skip copying boot image avb footer (boot partition size: 0, boot image size: 7700480).

我刷boot是没有这个提示的

**Comment by xsxsm** [comment]
> > 是不是这个问题呢，boot 没有刷成功skip  ？   Warning: skip copying boot image avb footer (boot partition size: 0, boot image size: 7700480).
> 
> 我刷boot是没有这个提示的

大佬，你可以用twrp打包一份吗，勾选所有分区，我下载恢复看看能不能行，感谢啦

**Comment by MarshJiang** [comment]
> > > 是不是这个问题呢，boot 没有刷成功skip  ？   Warning: skip copying boot image avb footer (boot partition size: 0, boot image size: 7700480).
> 
> > 
> 
> > 我刷boot是没有这个提示的
> 
> 
> 
> 大佬，你可以用twrp打包一份吗，勾选所有分区，我下载恢复看看能不能行，感谢啦

😂😂你刷了触屏也不能用，我因为屏幕不是原装，已经很久没管过这个项目了

**Comment by MarshJiang** [comment]
> > > 是不是这个问题呢，boot 没有刷成功skip  ？   Warning: skip copying boot image avb footer (boot partition size: 0, boot image size: 7700480).
> 
> > 
> 
> > 我刷boot是没有这个提示的
> 
> 
> 
> 大佬，你可以用twrp打包一份吗，勾选所有分区，我下载恢复看看能不能行，感谢啦

你可以去xda问问，那边有人刷成功了

**Comment by xsxsm** [comment]
> > > > 是不是这个问题呢，boot 没有刷成功skip ？ 警告：跳过复制启动映像 avb 页脚（启动分区大小：0，启动映像大小：7700480）。
> > 
> > 
> > > 
> > 
> > 
> > > 我刷boot是没有这个提示的
> > 
> > 
> > 大佬，你可以用twrp打包一份吗，勾选所有分区，我下载恢复看看能不能行，感谢啦
> 
> 😂😂你刷了触屏也不能用，我因为屏幕不是原装，已经很久没管过这个项目了

我可以不要触摸，能运行就行。

**Comment by xsxsm** [comment]
> > > > 是不是这个问题呢，boot 没有刷成功skip ？ 警告：跳过复制启动映像 avb 页脚（启动分区大小：0，启动映像大小：7700480）。
> > 
> > 
> > > 
> > 
> > 
> > > 我刷boot是没有这个提示的
> > 
> > 
> > 大佬，你可以用twrp打包一份吗，勾选所有分区，我下载恢复看看能不能行，感谢啦
> 
> 你可以去xda问问，那边有人刷成功了

好的感谢，我去注册一个xda账号

**Comment by MarshJiang** [comment]
> > > > > 是不是这个问题呢，boot 没有刷成功skip ？ 警告：跳过复制启动映像 avb 页脚（启动分区大小：0，启动映像大小：7700480）。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 我刷boot是没有这个提示的
> 
> > > 
> 
> > > 
> 
> > > 大佬，你可以用twrp打包一份吗，勾选所有分区，我下载恢复看看能不能行，感谢啦
> 
> > 
> 
> > 你可以去xda问问，那边有人刷成功了
> 
> 
> 
> 好的感谢，我去注册一个xda账号

xda里可能要等一段时间，别人才会回复，尽量用英文交流，不然老外看不懂。

**Comment by xsxsm** [comment]
> > > > > > 是不是这个问题呢，boot 没有刷成功skip ？ 警告：跳过复制启动映像 avb 页脚（启动分区大小：0，启动映像大小：7700480）。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 我刷boot是没有这个提示的
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 大佬，你可以用twrp打包一份吗，勾选所有分区，我下载恢复看看能不能行，感谢啦
> > 
> > 
> > > 
> > 
> > 
> > > 你可以去xda问问，那边有人刷成功了
> > 
> > 
> > 好的感谢，我去注册一个xda账号
> 
> xda里可能要等一段时间，别人才会回复，尽量用英文交流，不然老外看不懂。

我想要不自己从头构建，可以麻烦你写一下构建方法嘛？

**Comment by MarshJiang** [comment]
> > > > > > > 是不是这个问题呢，boot 没有刷成功skip ？ 警告：跳过复制启动映像 avb 页脚（启动分区大小：0，启动映像大小：7700480）。
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 我刷boot是没有这个提示的
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 大佬，你可以用twrp打包一份吗，勾选所有分区，我下载恢复看看能不能行，感谢啦
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 你可以去xda问问，那边有人刷成功了
> 
> > > 
> 
> > > 
> 
> > > 好的感谢，我去注册一个xda账号
> 
> > 
> 
> > xda里可能要等一段时间，别人才会回复，尽量用英文交流，不然老外看不懂。
> 
> 
> 
> 我想要不自己从头构建，可以麻烦你写一下构建方法嘛？

从头构建你可以去参考Postmarket OS的官方wiki，关于移植教程和主线内核那一块的，大佬记得耐心一点看，内容比较多

**Comment by MarshJiang** [comment]
> > > > > > > 是不是这个问题呢，boot 没有刷成功skip ？ 警告：跳过复制启动映像 avb 页脚（启动分区大小：0，启动映像大小：7700480）。
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 我刷boot是没有这个提示的
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 大佬，你可以用twrp打包一份吗，勾选所有分区，我下载恢复看看能不能行，感谢啦
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 你可以去xda问问，那边有人刷成功了
> 
> > > 
> 
> > > 
> 
> > > 好的感谢，我去注册一个xda账号
> 
> > 
> 
> > xda里可能要等一段时间，别人才会回复，尽量用英文交流，不然老外看不懂。
> 
> 
> 
> 我想要不自己从头构建，可以麻烦你写一下构建方法嘛？

https://postmarketos.org

**Comment by xsxsm** [comment]
> > > > > > > > 是不是这个问题呢，boot 没有刷成功skip ？ 警告：跳过复制启动映像 avb 页脚（启动分区大小：0，启动映像大小：7700480）。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > 我刷boot是没有这个提示的
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 大佬，你可以用twrp打包一份吗，勾选所有分区，我下载恢复看看能不能行，感谢啦
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 你可以去xda问问，那边有人刷成功了
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 好的感谢，我去注册一个xda账号
> > 
> > 
> > > 
> > 
> > 
> > > xda里可能要等一段时间，别人才会回复，尽量用英文交流，不然老外看不懂。
> > 
> > 
> > 我想要不自己从头构建，可以麻烦你写一下构建方法嘛？
> 
> 从头构建你可以去参考Postmarket OS的官方wiki，关于移植教程和主线内核那一块的，大佬记得耐心一点看，内容比较多

感谢感谢，你是大佬。 我还没弄过内核的东西，看着仓库里面的三个文件夹有点迷糊。 我现在就去看wiki

**Comment by MarshJiang** [comment]
This might help with that [boot signer for nubia nx563j](https://github.com/kindle4jerry/boot_signer_for_nubia_nx563j)

**Comment by LemonFan-maker** [comment]
> > > > 如题，我下载了release文件，解压后发现里面有boot 和 另一个文件。 我用twrp 刷入boot 和system 结果循环重启
> > > 
> > > 
> > > 这样算是刷完了吗，开机会无限重启，boot 是用twrp刷的哈。
> > > fastboot flash userdata C:\Users\xx\Desktop\nubia-nx563j.img
> > > Sending sparse 'userdata' 1/3 (494635 KB)          OKAY [ 16.531s]
> > > Writing 'userdata'                                 OKAY [ 36.800s]
> > > Sending sparse 'userdata' 2/3 (500188 KB)          OKAY [ 14.921s]
> > > Writing 'userdata'                                 OKAY [  7.185s]
> > > Sending sparse 'userdata' 3/3 (448023 KB)          OKAY [ 13.424s]
> > > Writing 'userdata'                                 OKAY [ 29.061s]
> > > Finished. Total time: 118.193s
> > 
> > 
> > 我自己是都是用fastboot刷的，你试试看
> 
> 感谢，我重新下载了release解压 然后C:\Users\xx> fastboot flash boot C:\Users\xx\Desktop\nx563j-postmarketos\nx563j-postmarketos\boot.img Warning: skip copying boot image avb footer (boot partition size: 0, boot image size: 7700480). Sending 'boot' (7520 KB) OKAY [ 0.191s] Writing 'boot' OKAY [ 0.072s] Finished. Total time: 0.271s
> 
> C:\Users\xx>fastboot flash userdata C:\Users\xx\Desktop\nx563j-postmarketos\nx563j-postmarketos\nubia-nx563j.img Sending sparse 'userdata' 1/3 (494635 KB) OKAY [ 20.740s] Writing 'userdata' OKAY [ 36.643s] Sending sparse 'userdata' 2/3 (500188 KB) OKAY [ 21.686s] Writing 'userdata' OKAY [ 7.162s] Sending sparse 'userdata' 3/3 (448023 KB) OKAY [ 19.304s] Writing 'userdata' OKAY [ 29.020s] Finished. Total time: 134.670s
> 
> C:\Users\xx>fastboot reboot Rebooting OKAY [ 0.000s] Finished. Total time: 0.001s 结果还是无限重启中

boot重新签名再刷
