### ISSUE TITLE
编译遇到问题

### ISSUE THREAD

**Issue by xsxsm** [Rikivt/postmarket_nubia_nx563j#3]
我用Debian10 安装了pmbootstrap  而且将本仓库文件拷贝到了testiing 目录下  。 执行这个 checksum  linux-nubia-nx563j，成功。 执行pmbootstrap build   linux-nubia-nx563j  失败  ：附上log
048089) [06:25:18] (native) % chown -R pmos:pmos /home/pmos/build
(048089) [06:25:18] % sudo umount /home/osboxes/.local/var/pmbootstrap/chroot_native/mnt/pmaports
(048089) [06:25:18] % sudo mount --bind /home/osboxes/.local/var/pmbootstrap/cache_git/pmaports /home/osboxes/.local/var/pmbootstrap/chroot_native/mnt/pmaports
(048089) [06:25:18] (native) % busybox su pmos -c HOME=/home/pmos mkdir -p /home/pmos/build
(048089) [06:25:18] (native) % busybox su pmos -c HOME=/home/pmos ln -sf /mnt/pmaports/.git /home/pmos/build/.git
(048089) [06:25:18] (native) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CROSS_COMPILE=aarch64-alpine-linux-musl- CC=aarch64-alpine-linux-musl-gcc GOCACHE=/home/pmos/.cache/go-build HOME=/home/pmos abuild -D postmarketOS -d
>>> linux-nubia-nx563j: Building pmos/linux-nubia-nx563j 6.1.0-r0 (using abuild 3.12.0-r0) started Sun, 03 Dec 2023 11:25:18 +0000
>>> linux-nubia-nx563j: Checking sanity of /home/pmos/build/APKBUILD...
>>> WARNING: linux-nubia-nx563j: No maintainer
>>> linux-nubia-nx563j: Cleaning up srcdir
>>> linux-nubia-nx563j: Cleaning up pkgdir
>>> linux-nubia-nx563j: Cleaning up tmpdir
>>> linux-nubia-nx563j: Fetching linux-nubia-nx563j-1d5659fd09334b7d2fefff845088aa97860a2274.tar.gz::https://gitlab.com/Rikivt/linux/-/archive/1d5659fd09334b7d2fefff845088aa97860a2274/linux-1d5659fd09334b7d2fefff845088aa97860a2274.tar.gz
>>> linux-nubia-nx563j: Fetching linux-nubia-nx563j-1d5659fd09334b7d2fefff845088aa97860a2274.tar.gz::https://gitlab.com/Rikivt/linux/-/archive/1d5659fd09334b7d2fefff845088aa97860a2274/linux-1d5659fd09334b7d2fefff845088aa97860a2274.tar.gz
>>> linux-nubia-nx563j: Checking sha512sums...
linux-nubia-nx563j-1d5659fd09334b7d2fefff845088aa97860a2274.tar.gz: OK
config-nubia-nx563j.aarch64: OK
>>> linux-nubia-nx563j: Unpacking /var/cache/distfiles/linux-nubia-nx563j-1d5659fd09334b7d2fefff845088aa97860a2274.tar.gz...
***
*** The source tree is not clean, please run 'make ARCH=arm64 mrproper'
*** in /home/pmos/build/src/linux-1d5659fd09334b7d2fefff845088aa97860a2274
***
make[2]: *** [../Makefile:586: outputmakefile] Error 1
/home/pmos/build/src/linux-1d5659fd09334b7d2fefff845088aa97860a2274/Makefile:711: include/config/auto.conf.cmd: No such file or directory
make[1]: *** [/home/pmos/build/src/linux-1d5659fd09334b7d2fefff845088aa97860a2274/Makefile:734: include/config/auto.conf] Error 2
make: *** [Makefile:222: __sub-make] Error 2
>>> ERROR: linux-nubia-nx563j: build failed
(048089) [06:25:27] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(048089) [06:25:27] NOTE: The failed command's output is above the ^^^ line in the log file: /home/osboxes/.local/var/pmbootstrap/log.txt
(048089) [06:25:27] ERROR: Command failed (exit code 1): (native) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CROSS_COMPILE=aarch64-alpine-linux-musl- CC=aarch64-alpine-linux-musl-gcc GOCACHE=/home/pmos/.cache/go-build HOME=/home/pmos abuild -D postmarketOS -d
(048089) [06:25:27] See also: <https://postmarketos.org/troubleshooting>
(048089) [06:25:27] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pmb/__init__.py", line 63, in main
    getattr(frontend, args.action)(args)
  File "/usr/local/lib/python3.7/dist-packages/pmb/helpers/frontend.py", line 116, in build
    args.strict, src=src):
  File "/usr/local/lib/python3.7/dist-packages/pmb/build/_package.py", line 505, in package
    suffix, src)
  File "/usr/local/lib/python3.7/dist-packages/pmb/build/_package.py", line 431, in run_abuild
    pmb.chroot.user(args, cmd, suffix, "/home/pmos/build", env=env)
  File "/usr/local/lib/python3.7/dist-packages/pmb/chroot/user.py", line 28, in user
    output_return, check, {}, auto_init)
  File "/usr/local/lib/python3.7/dist-packages/pmb/chroot/root.py", line 81, in root
    disable_timeout)
  File "/usr/local/lib/python3.7/dist-packages/pmb/helpers/run_core.py", line 390, in core
    check_return_code(args, code, log_message)
  File "/usr/local/lib/python3.7/dist-packages/pmb/helpers/run_core.py", line 252, in check_return_code
    log_message)
RuntimeError: Command failed (exit code 1): (native) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CROSS_COMPILE=aarch64-alpine-linux-musl- CC=aarch64-alpine-linux-musl-gcc GOCACHE=/home/pmos/.cache/go-build HOME=/home/pmos abuild -D postmarketOS -d

**Comment by MarshJiang** [comment]
> 我用Debian10 安装了pmbootstrap  而且将本仓库文件拷贝到了testiing 目录下  。 执行这个 checksum  linux-nubia-nx563j，成功。 执行pmbootstrap build   linux-nubia-nx563j  失败  ：附上log
> 
> 048089) [06:25:18] (native) % chown -R pmos:pmos /home/pmos/build
> 
> (048089) [06:25:18] % sudo umount /home/osboxes/.local/var/pmbootstrap/chroot_native/mnt/pmaports
> 
> (048089) [06:25:18] % sudo mount --bind /home/osboxes/.local/var/pmbootstrap/cache_git/pmaports /home/osboxes/.local/var/pmbootstrap/chroot_native/mnt/pmaports
> 
> (048089) [06:25:18] (native) % busybox su pmos -c HOME=/home/pmos mkdir -p /home/pmos/build
> 
> (048089) [06:25:18] (native) % busybox su pmos -c HOME=/home/pmos ln -sf /mnt/pmaports/.git /home/pmos/build/.git
> 
> (048089) [06:25:18] (native) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CROSS_COMPILE=aarch64-alpine-linux-musl- CC=aarch64-alpine-linux-musl-gcc GOCACHE=/home/pmos/.cache/go-build HOME=/home/pmos abuild -D postmarketOS -d
> 
> >>> linux-nubia-nx563j: Building pmos/linux-nubia-nx563j 6.1.0-r0 (using abuild 3.12.0-r0) started Sun, 03 Dec 2023 11:25:18 +0000
> 
> >>> linux-nubia-nx563j: Checking sanity of /home/pmos/build/APKBUILD...
> 
> >>> WARNING: linux-nubia-nx563j: No maintainer
> 
> >>> linux-nubia-nx563j: Cleaning up srcdir
> 
> >>> linux-nubia-nx563j: Cleaning up pkgdir
> 
> >>> linux-nubia-nx563j: Cleaning up tmpdir
> 
> >>> linux-nubia-nx563j: Fetching linux-nubia-nx563j-1d5659fd09334b7d2fefff845088aa97860a2274.tar.gz::https://gitlab.com/Rikivt/linux/-/archive/1d5659fd09334b7d2fefff845088aa97860a2274/linux-1d5659fd09334b7d2fefff845088aa97860a2274.tar.gz
> 
> >>> linux-nubia-nx563j: Fetching linux-nubia-nx563j-1d5659fd09334b7d2fefff845088aa97860a2274.tar.gz::https://gitlab.com/Rikivt/linux/-/archive/1d5659fd09334b7d2fefff845088aa97860a2274/linux-1d5659fd09334b7d2fefff845088aa97860a2274.tar.gz
> 
> >>> linux-nubia-nx563j: Checking sha512sums...
> 
> linux-nubia-nx563j-1d5659fd09334b7d2fefff845088aa97860a2274.tar.gz: OK
> 
> config-nubia-nx563j.aarch64: OK
> 
> >>> linux-nubia-nx563j: Unpacking /var/cache/distfiles/linux-nubia-nx563j-1d5659fd09334b7d2fefff845088aa97860a2274.tar.gz...
> 
> ***
> 
> *** The source tree is not clean, please run 'make ARCH=arm64 mrproper'
> 
> *** in /home/pmos/build/src/linux-1d5659fd09334b7d2fefff845088aa97860a2274
> 
> ***
> 
> make[2]: *** [../Makefile:586: outputmakefile] Error 1
> 
> /home/pmos/build/src/linux-1d5659fd09334b7d2fefff845088aa97860a2274/Makefile:711: include/config/auto.conf.cmd: No such file or directory
> 
> make[1]: *** [/home/pmos/build/src/linux-1d5659fd09334b7d2fefff845088aa97860a2274/Makefile:734: include/config/auto.conf] Error 2
> 
> make: *** [Makefile:222: __sub-make] Error 2
> 
> >>> ERROR: linux-nubia-nx563j: build failed
> 
> (048089) [06:25:27] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> (048089) [06:25:27] NOTE: The failed command's output is above the ^^^ line in the log file: /home/osboxes/.local/var/pmbootstrap/log.txt
> 
> (048089) [06:25:27] ERROR: Command failed (exit code 1): (native) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CROSS_COMPILE=aarch64-alpine-linux-musl- CC=aarch64-alpine-linux-musl-gcc GOCACHE=/home/pmos/.cache/go-build HOME=/home/pmos abuild -D postmarketOS -d
> 
> (048089) [06:25:27] See also: <https://postmarketos.org/troubleshooting>
> 
> (048089) [06:25:27] Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.7/dist-packages/pmb/__init__.py", line 63, in main
> 
>     getattr(frontend, args.action)(args)
> 
>   File "/usr/local/lib/python3.7/dist-packages/pmb/helpers/frontend.py", line 116, in build
> 
>     args.strict, src=src):
> 
>   File "/usr/local/lib/python3.7/dist-packages/pmb/build/_package.py", line 505, in package
> 
>     suffix, src)
> 
>   File "/usr/local/lib/python3.7/dist-packages/pmb/build/_package.py", line 431, in run_abuild
> 
>     pmb.chroot.user(args, cmd, suffix, "/home/pmos/build", env=env)
> 
>   File "/usr/local/lib/python3.7/dist-packages/pmb/chroot/user.py", line 28, in user
> 
>     output_return, check, {}, auto_init)
> 
>   File "/usr/local/lib/python3.7/dist-packages/pmb/chroot/root.py", line 81, in root
> 
>     disable_timeout)
> 
>   File "/usr/local/lib/python3.7/dist-packages/pmb/helpers/run_core.py", line 390, in core
> 
>     check_return_code(args, code, log_message)
> 
>   File "/usr/local/lib/python3.7/dist-packages/pmb/helpers/run_core.py", line 252, in check_return_code
> 
>     log_message)
> 
> RuntimeError: Command failed (exit code 1): (native) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CROSS_COMPILE=aarch64-alpine-linux-musl- CC=aarch64-alpine-linux-musl-gcc GOCACHE=/home/pmos/.cache/go-build HOME=/home/pmos abuild -D postmarketOS -d
> 
> 

麻烦你查看一下手机的具体硬件信息，上传一下，我确认一下是否有区别

**Comment by xsxsm** [comment]
这个可以吗
![微信图片_20231204104229](https://github.com/Rikivt/postmarket_nubia_nx563j/assets/32857774/952ee203-0372-424f-a7c9-4dafe3eb207a)

**Comment by xsxsm** [comment]
这个日志好像是说什么仓库不干净，为此我删除了PMos相关的东西，然后重启电脑再次尝试还是这样。 从这个日志来看是什么问题呢？

**Comment by MarshJiang** [comment]
> 这个可以吗
> 
> ![微信图片_20231204104229](https://github.com/Rikivt/postmarket_nubia_nx563j/assets/32857774/952ee203-0372-424f-a7c9-4dafe3eb207a)
> 
> 

要看到具体的型号，你这除了soc型号，啥都没有

**Comment by MarshJiang** [comment]
> 这个日志好像是说什么仓库不干净，为此我删除了PMos相关的东西，然后重启电脑再次尝试还是这样。 从这个日志来看是什么问题呢？

看这个[issue](https://github.com/Rikivt/postmarket_nubia_nx563j/issues/1)

**Comment by xsxsm** [comment]
> > 这个日志好像是说什么仓库不干净，为此我删除了PMos相关的东西，然后重启电脑再次尝试还是这样。 从这个日志来看是什么问题呢？
> 
> 看这个[issue](https://github.com/Rikivt/postmarket_nubia_nx563j/issues/1)

试了一下 ，不行  删了也报错     fatal error: asm/types.h no such file or dir

**Comment by MarshJiang** [comment]
> > > 这个日志好像是说什么仓库不干净，为此我删除了PMos相关的东西，然后重启电脑再次尝试还是这样。 从这个日志来看是什么问题呢？
> 
> > 
> 
> > 看这个[issue](https://github.com/Rikivt/postmarket_nubia_nx563j/issues/1)
> 
> 
> 
> 试了一下 ，不行  删了也报错     fatal error: asm/types.h no such file or dir

你编译出来也是这些东西，除非你准备自己写设备树。要先排除是硬件差异的问题

**Comment by xsxsm** [comment]
> > > > 这个日志好像是说什么仓库不干净，为此我删除了PMos相关的东西，然后重启电脑再次尝试还是这样。 从这个日志来看是什么问题呢？
> > 
> > 
> > > 
> > 
> > 
> > > 看这个[issue](https://github.com/Rikivt/postmarket_nubia_nx563j/issues/1)
> > 
> > 
> > 试了一下 ，不行  删了也报错     fatal error: asm/types.h no such file or dir
> 
> 你编译出来也是这些东西，除非你准备自己写设备树。要先排除是硬件差异的问题

问题已解决，需要在makedepends里加一个依赖：  linux-headers

**Comment by LemonFan-maker** [comment]
> 这个可以吗 ![微信图片_20231204104229](https://private-user-images.githubusercontent.com/32857774/287576220-952ee203-0372-424f-a7c9-4dafe3eb207a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTI3MDIsIm5iZiI6MTcyNDY1MjQwMiwicGF0aCI6Ii8zMjg1Nzc3NC8yODc1NzYyMjAtOTUyZWUyMDMtMDM3Mi00MjRmLWE3YzktNGRhZmUzZWIyMDdhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA2MDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOGU1MDBmNzVlNjhlYTRhZWNmYWViZjgwMDUzODE3NTM2YTM4NWQzY2U4MDU2MDIxM2YxMGM5ZmQwYmFmYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JjDNnGJSB2wus4D_PvYKdnI7QF6Y4aiYZCJyGe4VOtQ)

看了FP，应该可以
